### PR TITLE
Update angular to V18 and other updates

### PR DESCRIPTION
**Pull request by simonljus**
Cool project! 
Found this repository while [browsing  Reddit](https://www.reddit.com/r/beadsprites/comments/1g2cotr/amazing/) and saw that the project was open source. 

The latest Angular version is at this time when creating this PR at v18 so I gave it a try to update the entire project. 

Starting from Angular V9 to V18, updating one version at a time by following the [Angular Update Guide]( https://angular.dev/update-guide?v=9.0-18.0&l=1)

Major changes:
* Angular V9 -> 18
* TSLint -> Eslint 
* Yarn -> NPM. I could not get the Angular migrations to work properly and some issues when creating the docker image.
*  Tech debt: Migrate Angular flex layout -> css-fx-layout
*  Removed Webpack and Webpack Plugins (using vite now??)
*  Removed unused Dependencies
* Removed Google Analytics
* Updated Dockerfile
* ChartJS V2 -> V4
* Updated other packages
* Stricter Type Checking (mostly null checks)

### CODE REVIEW

**Comment by maxcleme** [comment]
I guess the only controversial change is removing GA. Any rationale?

**Comment by simonljus** [comment]
> I guess the only controversial change is removing GA. Any rationale?

I got some errors in the `environment.ts` file and I was also thinking if the solution was GDPR compliant.


I just took a look at some up to date guides to understand how it could be implemented in Angular 

One of many guides: 

https://medium.com/@onsignal/add-google-analytics-to-angular-in-5-simple-steps-8bb81d2d03b7



Info about how to make  it possible for the user to allow or deny tracking: 

(https://support.google.com/analytics/answer/9976101?hl=en)](https://support.google.com/analytics/answer/9976101?hl=en)

I think adding it back could be a new PR

**Comment by maxcleme** [comment]
Screenshot 2024-11-07 at 18 20 39

Looks like this is breaking the UI 😢

**Comment by simonljus** [comment]
I took a look at it,  seems to be an issue with `data-flex-xl`. Changed it to grid-layout instead using the same breakpoint values

**Comment by maxcleme** [comment]
Thank you so much for your contribution and for taking the time to submit this pull request. I really appreciate the effort you've put into it, and I apologize for the delay in getting back to you—things have been quite busy lately, and maintaining _beadifier_ isn't something I'm deeply invested in at the moment.

After reviewing your changes, I’ve decided not to proceed with merging this PR. While I truly value your interest in the project, this pull request includes a lot of changes at once, making it difficult to review effectively. Additionally, it introduces several visual changes that I’m not comfortable accepting, as they diverge from the current design direction.

If you’d like to continue contributing to beadifier, I’d recommend breaking changes into smaller, more focused pull requests. Narrowing the scope and keeping PRs atomic would make it much easier for me—or any future maintainers—to review and merge them.

I also recognize that the lack of tests in this repository is a limitation and makes external contributions more challenging. That’s entirely on me.

Here are the visual changes I noticed during my initial review. There may be others as well:

---

**global margins disappeared**

Screenshot 2024-11-22 at 22 03 30

Screenshot 2024-11-22 at 22 03 38

---

**dividers and combobox background**

Screenshot 2024-11-22 at 22 04 42
Screenshot 2024-11-22 at 22 04 34

---

**settings style**

Screenshot 2024-11-22 at 22 05 02
Screenshot 2024-11-22 at 22 05 10

---

**Usage screen layout**

Screenshot 2024-11-22 at 22 05 30
Screenshot 2024-11-22 at 22 05 39

---

Thank you again for your understanding and enthusiasm for the project. Please don’t hesitate to reach out if you’d like clarification or want to collaborate further.

**Pull request closed without merging**
